name: Lint

on:
  push:
  pull_request:

jobs:
  lint-self-hosted:
    name: Lint (self-hosted)
    runs-on: self-hosted
    steps: &lint-steps
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  lint-ubuntu:
    name: Lint (ubuntu fallback)
    needs: lint-self-hosted
    if: ${{ always() && needs.lint-self-hosted.result != 'success' }}
    runs-on: ubuntu-latest
    steps: *lint-steps
