name: Tests

on:
  push:
  pull_request:

jobs:
  test-self-hosted:
    name: Tests (self-hosted)
    runs-on: self-hosted
    continue-on-error: true
    steps: &test-steps
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Lint, vet, fmt, and test
        run: |
          go mod download
          make fmt
          make vet
          make lint
          make test

  test-ubuntu:
    name: Tests (ubuntu fallback)
    needs: test-self-hosted
    if: needs.test-self-hosted.result != 'success'
    runs-on: ubuntu-latest
    steps: *test-steps
